### ISSUE TITLE
can not connection

### ISSUE THREAD

**Issue by yokaimeow** [7ucifer66/7ucifer66.github.io#1]
Your blog can't visit

**Comment by 7ucifer66** [comment]
你不说我都没发现

**Comment by 7ucifer66** [comment]
> Your blog can't visit

你不说我都没发现

**Comment by yokaimeow** [comment]
然后在项目的简介里加个链接快速访问啊！！！！我还翻了CNAME才知道你的域名。

**Comment by yokaimeow** [comment]
还有解决了问题就把issue close

**Comment by 7ucifer66** [comment]
> 还有解决了问题就把issue close

好的好的

**Comment by 7ucifer66** [comment]
> 然后在项目的简介里加个链接快速访问啊！！！！我还翻了CNAME才知道你的域名。

我是想着写完第一篇再搞
